# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"test": "01_corner_detection_training.ipynb"}

modules = ["corner_detection.py"]

doc_url = "https://fastai.github.io/ocr/"

git_url = "https://github.com/fastai/ocr/tree/master/"

def custom_doc_links(name): return None
